version: "3.7"
services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    ports:
      - 8080:8080
    environment:
      AUTHENTICATION_API_KEY: B6D711FCDE4D4FD5936544120E713976